language: android
android:
  components:
    - build-tools-19.1.0

deploy:
  provider: releases
  api_key:
    secure: h/IJQeT3FtpzjVpxjG8Z1zY3BGhVy8GF5q0pHiBgah24MHbedOz60IxXstUxBjrmJmhMe95unURYN77WmN2wY+5MGtjdJXV49ntYc8KbLicjss36Pk8ce86e9LU9qH2mHIZfdVjTWdeFWJhBvGgJ/bBQDAb9ts0MDwVQRFJtfZI=
  file: syncloud/build/apk/syncloud-beta-release.apk
  skip_cleanup: true
  on:
    repo: syncloud/android
