language: java

before_install:
  - wget -O android-sdk-linux.tgz http://dl.google.com/android/android-sdk_r22.2.1-linux.tgz
  - tar -zxf android-sdk-linux.tgz
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${ANDROID_HOME}/build-tools/19.1.0:${ANDROID_HOME}/tools/proguard/bin
  - echo y | android update sdk --filter android-19,platform-tools,build-tools-19.1.0,extra-android-support,extra-android-m2repository,extra-google-m2repository --all --no-ui --force

deploy:
  provider: releases
  api_key:
    secure: h/IJQeT3FtpzjVpxjG8Z1zY3BGhVy8GF5q0pHiBgah24MHbedOz60IxXstUxBjrmJmhMe95unURYN77WmN2wY+5MGtjdJXV49ntYc8KbLicjss36Pk8ce86e9LU9qH2mHIZfdVjTWdeFWJhBvGgJ/bBQDAb9ts0MDwVQRFJtfZI=
  file: syncloud/build/apk/syncloud-beta-release.apk
  skip_cleanup: true
  on:
    repo: syncloud/android
